# Generated by Django 5.2.5 on 2025-09-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='producto_stock_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0), ('stock_minimo__isnull', True), _connector='OR'), name='producto_stock_minimo_gte_0_or_null'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__lte', models.F('stock')), ('stock_minimo__isnull', True), _connector='OR'), name='producto_stock_minimo_lte_stock_or_null'),
        ),
    ]
