# Generated by Django 5.2.5 on 2025-08-27 17:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['fecha'], name='compras_com_fecha_49ff0e_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['proveedor'], name='compras_com_proveed_07069f_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['usuario'], name='compras_com_usuario_5343bb_idx'),
        ),
        migrations.AddIndex(
            model_name='compraproducto',
            index=models.Index(fields=['compra'], name='compras_com_compra__c6dfb9_idx'),
        ),
        migrations.AddIndex(
            model_name='compraproducto',
            index=models.Index(fields=['producto'], name='compras_com_product_553722_idx'),
        ),
        migrations.AddConstraint(
            model_name='compraproducto',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='compra_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='compraproducto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='compra_precio_unitario_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='compraproducto',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0), ('descuento__lte', 100)), name='compra_descuento_0_100'),
        ),
    ]
