# Generated by Django 5.2.5 on 2025-08-28 16:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compraproducto',
            name='compra_descuento_0_100',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='impuesto',
            new_name='impuesto_total',
        ),
        migrations.RemoveField(
            model_name='compraproducto',
            name='descuento',
        ),
        migrations.AddField(
            model_name='compra',
            name='descuento_porcentaje',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='total_linea',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='compraproducto',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras.compra'),
        ),
    ]
